blank_issues_enabled: false
contact_links:
  - name: Feature request
    url: https://github.com/nexxonn-ai/nexxonn/discussions/categories/ideas
    about: Share ideas for new features
  - name: Ask a question
    url: https://github.com/nexxonn-ai/nexxonn/discussions/categories/q-a
    about: Ask questions and discuss with other community members
